### ISSUE TITLE
How to setup configuration

### ISSUE THREAD

**Issue by JanBliznicenko** [astares/Tealight#5]
Hello,
I would like to ask what is the recommended way to setup Teapot configuration.

When TLWebserver instance is created, initialize method creates Teapot instance with default configuration. Using the setter configuration: does not much, because the Teapot was already created with the default one.

What is the proper way to do this? Create subclass of TLWebserver with overridden defaultConfiguration?

**Comment by astares** [comment]
@JanBliznicenko 

If you just want to run on another port use 

```Smalltalk
TLWebserver startOn: 9092
```

And yes for an own custom config you can simply subclass and override #defaultConfiguration as the comment says:
```Smalltalk
defaultConfiguration 
	"Override to set more default values"

	^ { (#port -> self defaultPort) }
```
